defmodule Legend.Repo.Migrations.AddSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sessions, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :ended_at, :utc_datetime
      add :started_at, :utc_datetime
      add :error, :text
      add :exit_code, :bigint
      add :status, :text, null: false
      add :cwd, :text
      add :runtime_id, :text, null: false
      add :harness_id, :text, null: false
      add :name, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:sessions)
  end
end
