defmodule Legend.Repo.Migrations.AddRuntimeRefAndProvisioning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :runtime_ref, :map
    end
  end

  def down do
    alter table(:sessions) do
      remove :runtime_ref
    end
  end
end
