defmodule Legend.Repo.Migrations.AcpSessionFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :transport, :text, null: false, default: "terminal"
      add :conversation_id, :text
    end
  end

  def down do
    alter table(:sessions) do
      remove :conversation_id
      remove :transport
    end
  end
end
