defmodule Legend.Repo.Migrations.AddSessionMessagingFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :spawned_by_session_id, :uuid
      add :instructions, :text
      add :mcp_token, :text
    end
  end

  def down do
    alter table(:sessions) do
      remove :mcp_token
      remove :instructions
      remove :spawned_by_session_id
    end
  end
end
