defmodule Legend.Repo.Migrations.AddDevices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:devices, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec
      add :last_seen_at, :utc_datetime_usec
      add :paired_at, :utc_datetime_usec
      add :public_key, :text
      add :name, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:devices)
  end
end
