defmodule Legend.Repo.Migrations.AddPairingCodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pairing_codes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :redeemed_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec, null: false
      add :code, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:pairing_codes, [:code], name: "pairing_codes_unique_code_index")
  end

  def down do
    drop_if_exists unique_index(:pairing_codes, [:code], name: "pairing_codes_unique_code_index")

    drop table(:pairing_codes)
  end
end
