defmodule Legend.Repo.Migrations.AddMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :read_at, :utc_datetime
      add :payload, :text, null: false
      add :kind, :text, null: false
      add :to_session_id, :uuid, null: false
      add :from_session_id, :uuid
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:messages)
  end
end
