defmodule Legend.Repo.Migrations.AddAuditEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_events, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :action, :text, null: false
      add :session_id, :text
      add :device_id, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:audit_events)
  end
end
